### PR TITLE
docs: Point to the right NerdGraph Explorer instance for EU accounts

### PR DESCRIPTION
**Pull request by devurandom**
EU accounts need to use a special NerdGraph Explorer instance, cf. https://discuss.newrelic.com/t/cannot-create-personal-api-keys-via-nerdgraph-api-explorer/119069/5

### CODE REVIEW

**Comment by devurandom** [comment]
The failing builds are (as far as I can tell) not related to my changes:

> Error: Unable to process command '::add-path::/home/runner/go/bin' successfully.
> Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by zlesnr** [comment]
Thank you for the PR.  We fixed the add-path bits in master, so now I think the lint complaint is just that the commit doesn't conform.  Can you update the commit for this?

**Review by jthurman42 — APPROVED** [review]
Thanks for the contribution!

**Review by ctrombley — APPROVED** [review]
⚡

**Comment by ctrombley** [comment]
I am going to close this PR and fold the change into another with the updated commit convention.

**Comment by ctrombley** [comment]
The new PR for this is #1056.

**Pull request closed without merging**
