### PR TITLE
add slack as a notification channel

### LINKED ISSUE #1957: Add Slack as a notification destination type
### Feature Description
I would like to configure a Slack notification destination to use with the new Workflows.

### Describe Alternatives
The New Relic UI for configuring workflows and notification destinations allows Slack as a destination, but it is not documented as a supported type in the [New Relic Terraform provider docs](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination#type). I would love to use the same functionality in the Terraform provider that the UI provides instead of having to rely on a webhook.

### PR DESCRIPTION
**Pull request by rradillen**
# Description

Please include a summary of the change and which issue is fixed (if relevant).

Fixes #1957

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

Please delete options that are not relevant.

- [x] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] My code is formatted to [Go standards](https://go.dev/blog/gofmt)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests locally.

## How to test this change?

Create a slack destination in the UI interface (This cannot work IaC since OAuth doesn't work there).
Lookup it's id in NerdGraph.

Add a resource like below.

```resource "newrelic_notification_channel" "foo" {
  name = "foo"
  type = "SLACK"
  destination_id = "existing destination id"
  product = "IINT"

  property  {
    key = "channelId"
    value = "<channelid>"
  }

}`

### CODE REVIEW

**Comment by Dani-Relic** [comment]
@lzaga-newrelic please merge my changes to here ([draft PR](https://github.com/newrelic/terraform-provider-newrelic/pull/1979), I'll close it afterward)

**Comment by abennett** [comment]
Excited about this being completed. 👍

**Comment by arhill05** [comment]
Definitely looking for this one to be completed sooner rather than later. Having a manual webhook is not ideal!

**Comment by kohbis** [comment]
I'm looking for this PR will be merged as soon as possible!

**Comment by lzaga-newrelic** [comment]
Hi - there are some more logic to add for Slack - I did this [PR](https://github.com/newrelic/terraform-provider-newrelic/pull/1990) - which contains all.

**Review by lzaga-newrelic — CHANGES_REQUESTED** [review]
SLACK destination should only be imported to terraform (and cannot be created), due to authentication needs.

**Comment by kidk** [comment]
Thanks a lot for the PR @rradillen 

@lzaga-newrelic has added all these and more to an other PR. We should push out the release later today.

**Pull request closed without merging**
