### PR TITLE
Doc and domain updates

### PR DESCRIPTION
**Pull request by schmickie**
- update docs to include VIZ domain
- update docs to mention that all domains are searched if none is specified
- fix typo WORRKLOAD in docs
- add VIZ domain

### CODE REVIEW

**Comment by sanderblue** [comment]
Hi @schmickie, big thanks for the contribution! This updates look great, but it looks like we still need the CLA signed (super quick) and then one minor adjustment to the commit message, and then we can merge this. 

Can we reformat the commit message to follow the [conventional commits format](https://www.conventionalcommits.org/en/v1.0.0/#summary)? 

Essentially your commit message would read something like so:
```
fix(entity): add missing VIZ domain
```
(or something to that effect 😄)

Once we get those two things fixed, we'll be good to go. Thanks again!

**Comment by sanderblue** [comment]
Resolves: #849

**Comment by schmickie** [comment]
>  looks like we still need the CLA signed 

What does that mean and how do I do it?

> Can we reformat the commit message to follow the conventional commits format?

Do you know if there is a way to change a commit message after the fact?

**Comment by sanderblue** [comment]
Hi @schmickie, regarding the CLA, this pull request has an automated comment just below your first commit with a yellow button/badge you can click and then sign the our Contributor License Agreement (CLA). It will look similar to the image below. 😎 

CLA

Please feel free to check out our [Contributing to a New Relic Open Source Project] page for additional information as well. 

Regarding the commit messages, you can perform an interactive rebase to reword commit messages. GitHub has a help page with some information about performing an [interactive rebase](https://docs.github.com/en/github/using-git/using-git-rebase-on-the-command-line) that could help out there. 

In your case, while on your fork's master branch, you would probably run a command that looks like this: `git rebase --interactive HEAD~2`. Then git will give you a prompt and some options for how to proceed. Hope this helps 🙂

**Comment by schmickie** [comment]
Hey, I just took a look at the CLA, and I'm not willing to give out my personal info (address and phone number) for the purpose of submitting this PR. It looks like those pieces of information are not optional. If that's a blocker, then we'll need to just close out this PR. Sorry about that.

**Comment by zlesnr** [comment]
Hey @schmickie, when I signed the CLA, I used my work information.  I didn't want to give my personal address either.

**Comment by schmickie** [comment]
@zlesnr Good idea. I did it with my work's contact phone and address.

**Comment by schmickie** [comment]
I have tried the rebase several times and I keep getting all kinds of conflicts or other errors. I think it will just be easier for me to just close this PR, make a new fork, and try again.

**Comment by schmickie** [comment]
Here is the updated PR with the commit format as requested.

https://github.com/newrelic/terraform-provider-newrelic/pull/895

**Pull request closed without merging**
