### PR TITLE
feat: add s3 and docDb to AWS integration

### LINKED ISSUE #1956: Add S3 and DocDB to newrelic_cloud_aws_integrations
### Feature Description

S3 and DocDB are not fully supported by the Metric Stream. With S3 some buckets are not showing, as if they only emit usage data, they are not transmitted.

Without the DocDB polling, those entities are also not showing up in the Entity explorer of newrelic.

As both things are only working with the API Poll mechanism, it would be great if you can configure both via the `newrelic_cloud_aws_integrations`.

Then we could easily enable the exclusion of metric stream transmission for the relevant namespaces at the same time.

### PR DESCRIPTION
**Pull request by woehrl01**
# Description

Please include a summary of the change and which issue is fixed (if relevant).

Fixes #1956 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

Please delete options that are not relevant.

- [] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] My code is formatted to [Go standards](https://go.dev/blog/gofmt)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests locally.

## How to test this change?

Please describe how to test your changes. Include any relevant steps in the UI, HCL file(s), commands, etc

- Step 1
- Step 2
- etc

### CODE REVIEW

**Comment by shiva-bandari** [comment]
Hi @woehrl01,
Reviewed the code, the code looks good but the destroy functionality is not working

**Comment by shiva-bandari** [comment]
hi @woehrl01 

```
if _, ok := d.GetOk("vpc"); ok {
		cloudDisableAwsIntegration.Vpc = []cloud.CloudDisableAccountIntegrationInput{{LinkedAccountId: linkedAccountID}}
	}
```

need to add cloudDisableAwsIntegration.s3 same as the code shown above.

**Comment by woehrl01** [comment]
Thanks @shiva-bandari . I just added the missing parts for destroying.

**Comment by kidk** [comment]
@woehrl01 You'll need to change your last commit message `add delete input` to `chore: add delete input`. 

Ref: https://github.com/newrelic/terraform-provider-newrelic/blob/main/CONTRIBUTING.md#commit-messages

**Review by shiva-bandari — APPROVED** [review]

**Comment by kidk** [comment]
LGTM. Thanks a lot @woehrl01 We should have a release out later today.

**Pull request merged**
