### PR TITLE
docs: remove beta-specific info ahead of general release

### PR DESCRIPTION
**Pull request by mcmellawatt**
# Description

We are preparing general release of drop rules for metric aggregate attributes, so this PR removes the beta-specific blurb.

## Type of change

- [X] This change requires a documentation update

## Checklist:

- [X] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kidk — DISMISSED** [review]

**Comment by mbazhlekova** [comment]
@mcmellawatt Thanks for your contribution! One thing, can you reword the commit message to follow conventional commits? Maybe like `docs: remove beta info ahead of general release`

**Comment by mcmellawatt** [comment]
btw I am trying to sign the CLA and I get a screen where nothing is clickable or editable :(.  I tried in a couple different browsers.  Thoughts?

image

**Comment by mcmellawatt** [comment]
@mbazhlekova I fixed the commit message, but am running into the CLA problem above ^

**Comment by mcmellawatt** [comment]
Nevermind it finally loaded - signed!

**Comment by mbazhlekova** [comment]
@mcmellawatt The linter is picky about the commit message, can you add a space after `docs: `?

**Comment by mcmellawatt** [comment]
those merge commits kinda threw me off, i'm going to open a fresh PR for this

**Comment by mcmellawatt** [comment]
New PR: https://github.com/newrelic/terraform-provider-newrelic/pull/1647

**Pull request closed without merging**
